# Generated by Django 3.2.3 on 2021-05-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ww_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("is_on_special", models.BooleanField(default=False)),
                (
                    "previous_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "savings_amount",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("updated_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
